### PR TITLE
Support blocking mode for Go 1.10

### PR DESCRIPTION
**Pull request by monstermunchkin**
This reintroduces support for Go 1.10 but uses blocking mode instead.

LXD will be adding VM support which needs to work with Go 1.10 as well. See https://github.com/lxc/lxd/issues/6234.

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -12,8 +12,7 @@ This package supports varying levels of functionality depending on the version
 of Go used during compilation. The `Listener` and `Conn` types produced by this
 package are backed by non-blocking I/O, in order to integrate with Go's runtime
 network poller in Go 1.11+. Additional functionality is available starting in Go
-1.12+. Go 1.10 and prior versions of Go **are not supported** and will produce
-a compilation error when trying to build this package.
+1.12+.
```
Comment (mdlayher) [inline README.md]: Can you expand this documentation to indicate that 1.10 is supported in a blocking-only mode?

File: doc.go [hunk 2]
```diff
@@ -40,11 +40,6 @@
 //     - CloseRead and CloseWrite are not supported and will always return an error
 //     - SyscallConn is not supported and will always return an error
 //
```
Comment (mdlayher) [inline doc.go]: Please add a section on Go 1.10 behaviors.

File: fd_linux_1.10.go [hunk 3]
```diff
@@ -18,6 +19,16 @@ func (lfd *sysListenFD) accept4(flags int) (int, unix.Sockaddr, error) {
 	return unix.Accept4(lfd.fd, flags)
 }
 
+func (lfd *sysListenFD) setNonblocking(name string) error {
+	if err := unix.SetNonblock(lfd.fd, false); err != nil {
```
Comment (mdlayher) [inline fd_linux_1.10.go]: This should have a comment explaining that Go 1.10 cannot make use of non-blocking I/O. Same with sysConnFD equivalent.

**Comment by monstermunchkin** [comment]
Unfortunately, [staticcheck](honnef.co/go/tools/cmd/staticcheck) only supports the latest two Go versions therefore the Go 1.10 build fails.

File: .builds/go-1.10.yml [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+tasks:
+  - install: |
+      wget -q https://dl.google.com/go/go1.10.8.linux-amd64.tar.gz
+      sudo tar -C /usr/local -xzf go1.10.8.linux-amd64.tar.gz
+      sudo ln -s /usr/local/go/bin/go /usr/bin/go
+  - build: |
+      go version
+      cd vsock/
+      go get golang.org/x/lint/golint
+      go get honnef.co/go/tools/cmd/staticcheck
```
Comment (mdlayher) [inline .builds/go-1.10.yml]: I'd say it's fine to omit staticcheck on the 1.10.x build due to the use of newer APIs in the tool. We could potentially grab a release build, but I can handle that later.

File: doc.go [hunk 5]
```diff
@@ -40,10 +40,17 @@
...
-// Go 1.10 and below are not supported. The runtime network poller integration
-// required by this package is not available in Go versions prior to Go 1.11.
-// Unsupported versions of Go will produce a compilation error when trying to
-// build this package.
+// Go 1.10 (not recommended):
+//   - *Listener:
+//     - Accept is non-blocking and should be called in a loop, checking for
```
Comment (mdlayher) [inline doc.go]: Since Go 1.10 uses blocking I/O, this is not true yeah?

**Comment by mdlayher** [comment]
The 1.10 build appears to be failing due to no module mode support I'm guessing. GOPATH should work fine though once the dependencies are fetched.

**Comment by monstermunchkin** [comment]
What exactly needs to be changed in the build file for it to work?

**Comment by mdlayher** [comment]
Thanks for implementing this. I patched up the last couple of things with the CI build and integration tests.
